import asyncio

from pycryptoapi.bitunix import BitunixSocketManager, BitunixAdapter
from pycryptoapi.enums import MarketType, Exchange
from datetime import datetime


async def callback(msg):
    print(msg)

    a = BitunixAdapter.aggtrades_message(msg)

    print(a)


async def main():
    socket = BitunixSocketManager.aggtrades_socket(
        market_type=MarketType.FUTURES,
        tickers=['SUSHIUSDT', 'CGPTUSDT', 'BNTUSDT', 'BANKUSDT', 'MUBARAKUSDT', 'MILKUSDT', 'WAVESUSDT', 'XAIUSDT', 'SPELLUSDT', 'PNUTUSDT', 'DARUSDT', 'PENDLEUSDT', 'DEXEUSDT', 'AWEUSDT', 'KAIAUSDT', 'SHELLUSDT', 'REZUSDT', 'OLUSDT', 'GRIFFAINUSDT', '1000BONKUSDT', 'TRXUSDT', 'MORPHOUSDT', 'FHEUSDT', 'CHILLGUYUSDT', 'SAPIENUSDT', 'HMSTRUSDT', 'EPICUSDT', 'POLUSDT', 'UMAUSDT', 'OKBUSDT', 'OXTUSDT', 'APEUSDT', 'KEYUSDT', 'SKLUSDT', 'B2USDT', 'ZEREBROUSDT', 'PLUMEUSDT', 'ALTUSDT', 'SKYAIUSDT', 'MTLUSDT', 'VIRTUALUSDT', 'PROMUSDT', 'KILOUSDT', 'GUSDT', 'IDOLUSDT', 'CATIUSDT', 'HUMAUSDT', 'KSMUSDT', 'FORTHUSDT', 'TRBUSDT', 'MANAUSDT', 'NXPCUSDT', 'WUSDT', 'IPUSDT', 'ONDOUSDT', 'PIPPINUSDT', 'FORMUSDT', 'KOMAUSDT', 'SONICUSDT', 'STMXUSDT', 'TAUSDT', 'ENJUSDT', 'ZBCNUSDT', 'DRIFTUSDT', 'ENSUSDT', 'PUNDIXUSDT', 'AGIXUSDT', 'ZECUSDT', 'SYNUSDT', 'HYPEUSDT', '1000000MOGUSDT', 'SYRUPUSDT', 'GALAUSDT', 'AVAUSDT', 'VIDTUSDT', 'HIVEUSDT', 'TAGUSDT', 'MANTAUSDT', 'LISTAUSDT', 'LRCUSDT', 'FLRUSDT', 'HOMEUSDT', 'STGUSDT', 'STXUSDT', 'QNTUSDT', 'AIUSDT', 'STOUSDT', 'IOUSDT', 'TAOUSDT', 'ARUSDT', 'B3USDT', 'FILUSDT', 'ZETAUSDT', 'FIDAUSDT', 'MEMEFIUSDT', 'TRUMPUSDT', 'PUMPUSDT', 'SOLUSDT', 'AUSDT', 'AXLUSDT', 'LOOMUSDT', '1000WHYUSDT', '1000SATSUSDT', 'COMBOUSDT', 'GMTUSDT', 'BANDUSDT', 'RPLUSDT', 'CRVUSDT', 'VOXELUSDT', 'BONDUSDT', 'SLERFUSDT', 'DOTUSDT', 'ACXUSDT', 'WALUSDT', 'TEST1USDT', 'APTUSDT', 'FRONTUSDT', 'SEIUSDT', 'FUSDT', 'BIOUSDT', 'XUSDT', 'REDUSDT', 'MEMEUSDT', 'KMNOUSDT', 'HOTUSDT', 'MOODENGUSDT', 'AIXBTUSDT', 'COREUSDT', 'QTUMUSDT', 'AVAAIUSDT', 'IOTAUSDT', 'TREEUSDT', 'TESTUSDT', 'ZROUSDT', 'XCNUSDT', 'BIGTIMEUSDT', 'HYPERUSDT', 'ETHFIUSDT', 'MUSDT', 'SKATEUSDT', 'USTCUSDT', 'THEUSDT', 'ETHUSDT', 'ORDIUSDT', 'WOOUSDT', 'HIPPOUSDT', 'SWARMSUSDT', 'CFXUSDT', 'FXSUSDT', 'BUSDT', 'PUFFERUSDT', 'POWRUSDT', 'NEOUSDT', 'UNFIUSDT', 'MINAUSDT', 'TAIKOUSDT', 'LAUNCHCOINUSDT', 'SPKUSDT', 'CELRUSDT', 'AGLDUSDT', 'RSRUSDT', 'ICNTUSDT', 'RENUSDT', 'NOTUSDT', 'RESOLVUSDT', 'PHBUSDT', 'NEWTUSDT', 'PUMPFUNUSDT', 'EGLDUSDT', 'LUNA2USDT', 'PORT3USDT', 'LQTYUSDT', 'COTIUSDT', 'VANRYUSDT', 'A2ZUSDT', 'FLMUSDT', 'TUTUSDT', 'EOSUSDT', '1MBABYDOGEUSDT', 'SUIUSDT', 'METISUSDT', 'DENTUSDT', 'TRUUSDT', 'MERLUSDT', 'C98USDT', 'BRETTUSDT', 'HAEDALUSDT', 'TWTUSDT', 'GUNUSDT', 'PIUSDT', 'BEAMXUSDT', 'BCHUSDT', 'FIOUSDT', 'BOMEUSDT', '1000SHIBUSDT', 'SLPUSDT', 'BERAUSDT', 'KAITOUSDT', 'ETHWUSDT', 'CUSDT', 'BICOUSDT', 'TONUSDT', '1000LUNCUSDT', 'RADUSDT', 'TURBOUSDT', 'BABYUSDT', 'BDXNUSDT', 'AVAXUSDT', 'PARTIUSDT', 'RFCUSDT', 'JUPUSDT', 'MOVRUSDT', 'MATICUSDT', 'OMUSDT', 'ONGUSDT', 'XVGUSDT', 'TIAUSDT', 'MKRUSDT', 'THETAUSDT', 'UNIUSDT', 'PERPUSDT', 'ARKMUSDT', 'RVNUSDT', 'COMPUSDT', '1000PEPEUSDT', 'FETUSDT', '1000RATSUSDT', 'BANANAS31USDT', 'LEVERUSDT', 'MLNUSDT', 'CROUSDT', 'SXPUSDT', 'ZILUSDT', 'AXSUSDT', 'CHZUSDT', 'ILVUSDT', 'KASUSDT', 'ACHUSDT', 'XPLUSDT', 'VELODROMEUSDT', 'VTHOUSDT', 'FUNUSDT', 'VINEUSDT', 'INJUSDT', 'LUMIAUSDT', 'EIGENUSDT', 'INITUSDT', 'SAGAUSDT', 'ZORAUSDT', 'RDNTUSDT', 'ZRXUSDT', 'NILUSDT', 'HIGHUSDT', 'BNBUSDT', 'XTZUSDT', 'MEWUSDT', 'JOEUSDT', 'XMRUSDT', 'ETCUSDT', 'MEUSDT', 'MNTUSDT', 'ALICEUSDT', 'AEROUSDT', 'HOOKUSDT', 'ACEUSDT', 'TOWNSUSDT'],
        callback=callback,
    )

    await socket.start()


asyncio.run(main())
